# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 14:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanadaShape',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('csdname', models.TextField(blank=True, null=True)),
                ('ccsuid', models.IntegerField(blank=True, max_length=10, null=True)),
                ('prname', models.TextField(blank=True, max_length=10, null=True)),
                ('ccsname', models.TextField(blank=True, max_length=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'canadashape',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('males', models.IntegerField()),
                ('females', models.IntegerField()),
            ],
        ),
    ]
