# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cancommute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routedestination', to='cancommute.CanadaShape'),
        ),
        migrations.AddField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routeorigin', to='cancommute.CanadaShape'),
        ),
    ]
