# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 20:32
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancommute', '0002_auto_20170823_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
