# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-23 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancommute', '0003_route_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='females',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='males',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
