# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_authority_name', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_authority_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxServicePropertyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('billing_authority_code', models.CharField(blank=True, max_length=25, null=True)),
                ('total_area_m2_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('total_area_m2_unit_num', models.FloatField(blank=True, null=True)),
                ('price_per_m2_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('price_per_m2_unit_num', models.FloatField(blank=True, null=True)),
                ('current_rateable_value', models.CharField(blank=True, max_length=50, null=True)),
                ('current_rateable_value_num', models.FloatField(blank=True, null=True)),
                ('lsoa_name', models.CharField(blank=True, max_length=254, null=True)),
                ('lsoa_code', models.CharField(blank=True, max_length=254, null=True)),
                ('billing_authority_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.BillingAuthority')),
                ('building_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scrape.BuildingType')),
            ],
            options={
                'db_table': 'tax_service_property_information',
            },
        ),
    ]
