# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-23 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingtype',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
